// Generated by optioner -type Example; DO NOT EDIT
// If you have any questions, please create issues and submit contributions at:
// https://github.com/chenmingyong0423/go-optioner

package example

type ExampleOption[T any] func(*Example[T])

func NewExample[T any](a T, opts ...ExampleOption[T]) *Example[T] {
	example := &Example[T]{
		A: a,
	}

	for _, opt := range opts {
		opt(example)
	}

	return example
}

func WithB[T any](b T) ExampleOption {
	return func(example *Example) {
		example.B = b
	}
}

func WithC[T any](c int) ExampleOption {
	return func(example *Example) {
		example.C = c
	}
}
