// Generated by optioner -type GenericExample; DO NOT EDIT
// If you have any questions, please create issues and submit contributions at:
// https://github.com/chenmingyong0423/go-optioner

package example

type GenericExampleOption[T any, U comparable, V ~int] func(*GenericExample[T, U, V])

func NewGenericExample[T any, U comparable, V ~int](a T, opts ...GenericExampleOption[T, U, V]) *GenericExample[T, U, V] {
	genericExample := &GenericExample[T, U, V]{
		A: a,
	}

	for _, opt := range opts {
		opt(genericExample)
	}

	return genericExample
}

func WithB[T any, U comparable, V ~int](b U) GenericExampleOption[T, U, V] {
	return func(genericExample *GenericExample[T, U, V]) {
		genericExample.B = b
	}
}

func WithC[T any, U comparable, V ~int](c V) GenericExampleOption[T, U, V] {
	return func(genericExample *GenericExample[T, U, V]) {
		genericExample.C = c
	}
}

func WithD[T any, U comparable, V ~int](d string) GenericExampleOption[T, U, V] {
	return func(genericExample *GenericExample[T, U, V]) {
		genericExample.D = d
	}
}
